language: python
python:
  - '2.7'
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
  - "pypy3"
before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-dev erlang-dev
install:
  - python setup.py install
script:
  - python setup.py build
notifications:
  email:
    recipients:
      - mjtruog@gmail.com
  irc:
    channels:
      - "chat.freenode.net#cloudi"
    template:
      - "%{repository_slug} (%{branch} - %{commit}) %{author}: %{commit_message}"
      - "View Changes %{compare_url}"
      - "Build #%{build_number}: %{message} (%{build_url})"
    on_success: change
    on_failure: always
