language: python
python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'
before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-dev
install:
  - python setup.py install
script:
  - python setup.py test
